### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by eikaramba** [petrosDemetrakopoulos/ethairballoons#11]
hey thanks for that library, really cool. i tried to use it and finally got it working but found some issues i want to share:

- maybe switch to promises or at least change the order of the returned parameters, as currently you are returning the error as the second argument, which is wrong. the standard is to return as the first argument, otherwise the standard promisify function of node does not work correctly https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original
- i needed to change the template and use `pragma solidity >=0.6.2;` otherwise it would not compile
- would it be possible to switch to es6 modules instead of commonjs require modules?

**Comment by petrosDemetrakopoulos** [comment]
Thank you very much for your comments ! I will check the issues and come back to you as soon as yhey are fixed.

**Comment by petrosDemetrakopoulos** [comment]
Hello, thanks again for the constructive comments and suggestions.

- Regarding the first point, I changed the callbacks to error-first style in order to be compliant with the standard.
- Regarding the second point I updated the template to `pragma solidity >=0.6.2;`, however it was working correctly at my setup. Probably it is related to the installed version of ganache.
- Regarding the 3rd point, I am very reluctant to change to es6 import modules as some versions of node.JS that are still heavily used do not support this style.
- Finally, given the chance of some changes in the library I updated some dependencies (solc, web3, mocha and eslint)

All changes mentioned above have been pushed to the master branch. Please have a look and if everything is OK let me know in order to publish an updated version o the library.

Thanks again,
Petros.

**Comment by eikaramba** [comment]
wow cool, thank you very much. in regards to the solidity error i installed the stable `npm install -g ganache-cli` version. that one was given me an error that the compiler version does not match or something like that.

i understand to wait for es6 modules.
